blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Submit a New Prompt
    url: https://prompts.chat/prompts/new
    about: Please submit new prompts via our website automation.
  - name: ğŸ› Report a Bug / Spam
    url: https://github.com/f/prompts.chat/issues/new?title=Report:%20
    about: Report spam or issues with the repository.
